# Generated by Django 4.0.3 on 2022-03-15 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_mobile_number', models.CharField(max_length=200)),
                ('customer_email_address', models.CharField(max_length=200)),
                ('customer_creation_date', models.DateTimeField(auto_now_add=True)),
                ('customer_update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('personnel_id_number', models.CharField(max_length=200)),
                ('personnel_name', models.CharField(max_length=200)),
                ('personnel_daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('personnel_qualification', models.CharField(choices=[('Diploma', 'Diploma'), ('Degree', 'Degree')], max_length=200)),
                ('personnel_role', models.CharField(choices=[('Forklift Operator', 'Forklift Operator'), ('Driver', 'Driver')], max_length=200)),
                ('personnel_creation_date', models.DateTimeField(auto_now_add=True)),
                ('personnel_update_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('contract_start_date', models.DateTimeField(auto_now_add=True)),
                ('contract_end_date', models.DateTimeField(auto_now_add=True)),
                ('contract_last_update_date', models.DateTimeField(auto_now=True)),
                ('contract_max_km_per_trip', models.DecimalField(decimal_places=2, max_digits=2)),
                ('contract_overage_charge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contract_customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleetManagement.customer')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('asset_tracker_id', models.CharField(max_length=200)),
                ('asset_name', models.CharField(max_length=200)),
                ('asset_type', models.CharField(choices=[('Forklift', 'Forklift'), ('Vehicle', 'Vehicle')], max_length=200)),
                ('asset_model', models.CharField(max_length=200)),
                ('asset_registration_number', models.CharField(max_length=200)),
                ('asset_daily_selling_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('asset_assigned_personnel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleetManagement.personnel')),
                ('asset_contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fleetManagement.contract')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
