# Generated by Django 4.0.3 on 2022-03-15 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleetManagement', '0002_alter_contract_contract_max_km_per_trip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contract_end_date',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
