# Generated by Django 4.0.3 on 2022-03-15 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fleetManagement', '0005_alter_contract_contract_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fleetManagement.contract'),
        ),
    ]
